### ISSUE TITLE
No checkbox when sending email- yet in the error message

### ISSUE THREAD

**Issue by keshashah** [systers/crowdmap#25]
In this issue, when you try to send a message without email address - the error message - "The Email field is required if the checkbox is checked." is displayed. Though there is no checkbox displayed, which is checked.

Steps to Reproduce -

1. Go to Contact us Page
2. Fill in all details except the email address field
3, Click on Send Message button.

Screencast: http://screencast.com/t/AD7J1Ze7

**Comment by rosariorobinson** [comment]
The same as before, I click on the link, but nothing happens when I play the screencast.

**Comment by keshashah** [comment]
The video works for me on firefox. I don't know why it isn't working on your end. However, steps to reproduce are simple. And I am attaching screenshot for reference. Let me know if you have queries.

![image](https://cloud.githubusercontent.com/assets/2563540/8551836/9f891fba-24f6-11e5-99e7-b85796f3e314.png)

**Comment by jproft** [comment]
For this one, the issue is that the same error text from the alerts page is recycled for the contact page. On the alerts page, there is a checkbox, so the error message makes sense in that context, but it doesn't make sense here. I've changed the corresponding string in the i18n files accordingly.

**Comment by keshashah** [comment]
Thanks @jproft :+1:
